version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.0

jobs:
  install:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/react-chat
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/react-chat
          paths:
            - node_modules

  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/react-chat
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-chat
      - run:
          name: Build application
          command: npm run build
      - persist_to_workspace:
          root: ~/react-chat
          paths:
            - build

  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-chat
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: aws s3 sync build s3://chatbot-lex-bucket

workflows:
  version: 2
  deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - cypress/run:
          start: npm start
          wait-on: 'http-get://localhost:3000'
          store_artifacts: true
          requires:
            - build
      - deploy:
          requires:
            - cypress/run
